# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Parameter.create(name: 'savory', savory: 6)
Parameter.create(name: 'butter', savory: 6)
Parameter.create(name: 'brown butter', savory: 6)
Parameter.create(name: 'beer', savory: 6)
Parameter.create(name: 'almond', savory: 6)
Parameter.create(name: 'olive oil', savory: 6)
Parameter.create(name: 'chestnut', savory: 6)
Parameter.create(name: 'straw', savory: 6)
Parameter.create(name: 'leather', savory: 6)
Parameter.create(name: 'curry', savory: 6)
Parameter.create(name: 'lanolin', savory: 6)
Parameter.create(name: 'bread', savory: 6)
Parameter.create(name: 'hazelnut', savory: 6)
Parameter.create(name: 'walnut', savory: 6)
Parameter.create(name: 'soy sauce', savory: 6)
Parameter.create(name: 'miso', savory: 6)
Parameter.create(name: 'yeast', savory: 6)
Parameter.create(name: 'potato', savory: 6)
Parameter.create(name: 'nutty', savory: 6)
Parameter.create(name: 'tobacco', savory: 6)
Parameter.create(name: 'peanut butter', savory: 6)

Parameter.create(name: 'yogurt', sour: 6)
Parameter.create(name: 'creme fraiche', sour: 6)
Parameter.create(name: 'orange', sour: 6)
Parameter.create(name: 'citrus', sour: 6)
Parameter.create(name: 'wine', sour: 6)
Parameter.create(name: 'sharp', sour: 6)
Parameter.create(name: 'artichoke', sour: 6)
Parameter.create(name: 'acidic', sour: 6)
Parameter.create(name: 'sour', sour: 6)
Parameter.create(name: 'lactic', sour: 6)

Parameter.create(name: 'greens', bitter: 6)
Parameter.create(name: 'mushrooms', bitter: 6)
Parameter.create(name: 'moss', bitter: 6)
Parameter.create(name: 'stony', bitter: 6)
Parameter.create(name: 'grass', bitter: 6)
Parameter.create(name: 'black pepper', bitter: 6)
Parameter.create(name: 'chili', bitter: 6)
Parameter.create(name: 'coffee', bitter: 6)
Parameter.create(name: 'espresso', bitter: 6)
Parameter.create(name: 'earth', bitter: 6)
Parameter.create(name: 'mold', bitter: 6)
Parameter.create(name: 'ammonia', bitter: 6)
Parameter.create(name: 'bitter', bitter: 6)

Parameter.create(name: 'metallic', salty: 6)
Parameter.create(name: 'mineral', salty: 6)
Parameter.create(name: 'garlic', salty: 6)
Parameter.create(name: 'saline', salty: 6)

Parameter.create(name: 'barnyard', funky: 6)
Parameter.create(name: 'goaty', funky: 6)
Parameter.create(name: 'sweat', funky: 6)
Parameter.create(name: 'feet', funky: 6)
Parameter.create(name: 'broth', funky: 6)
Parameter.create(name: 'smoke', funky: 6)
Parameter.create(name: 'manure', funky: 6)
Parameter.create(name: 'butyric', funky: 6)
Parameter.create(name: 'feline', funky: 6)
Parameter.create(name: 'funky', funky: 6)
Parameter.create(name: 'band-aid', funky: 6)

Parameter.create(name: 'celery', sweet: 6)
Parameter.create(name: 'onion', sweet: 6)
Parameter.create(name: 'toffee', sweet: 6)
Parameter.create(name: 'nutmeg', sweet: 6)
Parameter.create(name: 'vanilla', sweet: 6)
Parameter.create(name: 'chocolate', sweet: 6)
Parameter.create(name: 'thistle', sweet: 6)
Parameter.create(name: 'sweet', sweet: 6)
Parameter.create(name: 'berry', sweet: 6)
Parameter.create(name: 'apple', sweet: 6)
Parameter.create(name: 'pear', sweet: 6)
Parameter.create(name: 'stone fruit', sweet: 6)
Parameter.create(name: 'melon', sweet: 6)
Parameter.create(name: 'pineapple', sweet: 6)
Parameter.create(name: 'mango', sweet: 6)
Parameter.create(name: 'banana', sweet: 6)
Parameter.create(name: 'cider', sweet: 6)
Parameter.create(name: 'floal', sweet: 6)
Parameter.create(name: 'honey', sweet: 6)
Parameter.create(name: 'mint', sweet: 6)
Parameter.create(name: 'fennel', sweet: 6)
Parameter.create(name: 'rosemary', sweet: 6)